### ISSUE TITLE
Error updating chart calling addSeries method

### ISSUE THREAD

**Issue by javifm86** [mkdudeja/angular-highcharts-chart#1]
Hi,

I am using angular-highcharts-chart wrapper into a panel component for rendering charts. When I open a panel, new chart is rendered(inside panel-body component). I have 3 panels for example, each time I open the panel new chart is rendered ok.

I find the problem when I try to modify a chart, I call **addSeries** method for highcharts, but the change is always rendered in the first chart created. Same occurs if I change the object **[options]** and I update **[(update)]** to true.

I am not sure if this is wrapper problem or from highcharts official plugin, I couldn´t try official wrapper because it does´t work with Angular 6.

Thanks for all. Best regards.

**Comment by mkdudeja** [comment]
To best of my knowledge it should be from official highchart plugin, this plugin is just a wrapper over the original.

I am going busy with the things right now. So, won't be able to help much but try my best to look into.

**Comment by javifm86** [comment]
Thanks, I have isolated the use case in another empty project and I can´t reproduce it, so the conclusion is that I must have an error logic in my app. Sorry, I should have isolated the use case before posting an issue.

Thanks for all and excuse me.
